name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql user: 'nociza'
          mysql password: 'password'
      - name: Run tests
        run: cargo test --verbose
