name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      MYSQL_DATABASE_URL: mysql://root:password@localhost:3306/test_db
    steps:
      - name: Wait for MySQL to start
        run: |
          until docker exec mysql mysqladmin ping --silent; do
            echo 'Waiting for MySQL to start...'
            sleep 1
          done
      - name: Create test database
        run: docker exec -i mysql mysql -u root -p password -e 'CREATE DATABASE test;'
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --verbose
